name: Rust Check Format and Lint

on:
  push:
    branches: 
      - main
      - develop
      - feature/*
      - bugfix/* 

  pull_request:
    branches: 
      - main
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  LintAndFormat:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Format
      run: cargo fmt --check
    - name: Lint 
      run: cargo clippy
    - uses: Swatinem/rust-cache@v1